name: Create item in GitHub Project

on:
  issues: 
    types: [ opened, reopened ]

jobs:
  create-item:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          ORGANIZATION: dvalleit
          PROJECT_NUMBER: 3
          NUMBER: ${{ github.event.issue.number }}
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!){
              organization(login: $org){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER
