name: Create item in GitHub Project

on:
  issues: 
    types: [ opened, reopened ]

jobs:
  create-item:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to GH Project
        run: |
          echo $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
